# The goal of this collection is to offer a quick reference

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)

1.25.2


#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_arr = np.zeros(10)
print(null_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
print(null_arr.nbytes)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null_vector = np.zeros(10)

null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
vec = np.arange(10,50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
rev_vec = vec [::-1]
print(rev_vec)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
x = np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])

nonzero_indices = np.nonzero(arr)

print("Indices of non-zero elements:", nonzero_indices)

Indices of non-zero elements: (array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
identity = np.eye(3,3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
random_arr = np.random.rand(3,3,3)
print(random_arr)

[[[0.65780952 0.6817356  0.92791495]
  [0.87845893 0.65753886 0.81317776]
  [0.69293496 0.09954408 0.05486643]]

 [[0.21516722 0.22008435 0.50305215]
  [0.83985444 0.38858769 0.69721251]
  [0.59587118 0.46467223 0.23168722]]

 [[0.17710464 0.06623587 0.64166534]
  [0.28834953 0.89434009 0.42441627]
  [0.9221602  0.79891524 0.71293687]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
random_arr2 = np.random.rand(10,10)
print(random_arr2.max())
print(random_arr2.min())

0.9906472441037347
0.0008697614438865076


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
random_vec = np.random.rand(1,30)
print(random_vec.mean())

0.5310914953370307


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
rows = 5
cols = 5

array = np.zeros((rows, cols), dtype=int)

array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1

print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
array2 = np.ones((rows, cols), dtype=int)

array2[0, :] = 0
array2[-1, :] = 0
array2[:, 0] = 0
array2[:, -1] = 0

print(array2)

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
# nan
# false
# false
# nan
# true
# false

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
matrix = np.zeros((5, 5), dtype=int)

np.fill_diagonal(matrix[1:] , np.array([1, 2, 3, 4]))

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
matrix = np.zeros((8, 8), dtype=int)

matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
shape = (6, 7, 8)

flat_index = 99

indices = np.unravel_index(flat_index, shape)

print("Index (x, y, z):", indices)

Index (x, y, z): (1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
tile = np.array([[0, 1], [1, 0]])

checkerboard = np.tile(tile, (4, 4))

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
random_matrix = np.random.rand(5, 5)

total_sum = np.sum(random_matrix)

normalized_matrix = random_matrix / total_sum

print("Matrix after normalization:")
print(normalized_matrix)

Matrix after normalization:
[[0.01751604 0.07339391 0.00423523 0.01432775 0.06722406]
 [0.02381672 0.02235475 0.07431158 0.05380301 0.01543617]
 [0.05982375 0.02429233 0.07951207 0.07036939 0.03224461]
 [0.02434838 0.06819567 0.00164446 0.05049038 0.01374725]
 [0.04769682 0.00926796 0.06948158 0.00717364 0.07529247]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])

print("Custom RGBA dtype:", color_dtype)

Custom RGBA dtype: [('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
arr1 = np.random.rand(5 , 3)
arr2 = np.random.rand(3 , 2)

pro_arr = np.dot(arr1 , arr2)

print(pro_arr)

[[0.80216662 1.31586909]
 [0.8463166  1.58535375]
 [0.71142916 1.21514321]
 [0.46798179 0.95697109]
 [0.72733435 1.39188872]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

arr[(arr > 3) & (arr < 8)] *= -1

print("Modified array:")
print(arr)

Modified array:
[ 1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
# 9
# 10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
# Z**Z
# 2 << Z >> 2
# Z <- Z
# Z/1/1
# Z<Z>Z

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
# nan
# nan
a = np.array([np.nan]).astype(int).astype(float)
print (a)

[-9.22337204e+18]


<ipython-input-3-25d775166b7e>:3: RuntimeWarning: invalid value encountered in cast
  a = np.array([np.nan]).astype(int).astype(float)


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
float_array = np.array([-3.2, -2.5, -1.8, 0, 1.8, 2.5, 3.2])

rounded_array = np.ceil(float_array)

print(rounded_array)

[-3. -2. -1.  0.  2.  3.  4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
x = np.array([1,2,3,4,5])
x2 = np.array([5,6,7,8,9])
x3 = np.intersect1d(x,x2)

print(x3)

[5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
# import warnings

# warnings.filterwarnings("ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


<ipython-input-7-c6ff0ad7fd7b>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
today = np.datetime64('today')

yesterday = today - np.timedelta64(1, 'D')

tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2024-04-26
Today: 2024-04-27
Tomorrow: 2024-04-28


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
start_date = np.datetime64('2016-07-01')
end_date = np.datetime64('2016-08-01')

dates = np.arange(start_date, end_date, dtype='datetime64[D]')

print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.array([1, 2, 3],dtype = np.float64)
B = np.array([4, 5, 6])

np.multiply(A, -1*A/2, out=A)
np.add(A, B, out=A)

print(A)

[3.5 3.  1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
x = np.array([1.4 , 1.3 , 2.5 , 3.8 , 4,7])

print(np.floor(x))

[1. 1. 2. 3. 4. 7.]


In [ ]:
print(np.trunc(x))

[1. 1. 2. 3. 4. 7.]


In [ ]:
integer_part = np.where(x < 0, np.ceil(x), np.floor(x))

print("Method 3 (np.ceil and np.floor):", integer_part)

Method 3 (np.ceil and np.floor): [1. 1. 2. 3. 4. 7.]


In [ ]:
integer_part = x.astype(int)

print("Method 4 (np.astype(int)):", integer_part)

Method 4 (np.astype(int)): [1 1 2 3 4 7]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
row_values = np.arange(5)

matrix = row_values[:, np.newaxis] * np.ones(5)

print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
x = (np.random.rand(1,10) * 10).astype(int)

print(x)

[[1 8 9 7 5 9 7 4 5 3]]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
x = np.random.rand(1,10)
print(x)

[[0.02414255 0.86280993 0.33927883 0.02390773 0.1634656  0.32423852
  0.12634595 0.94491383 0.86175287 0.28382233]]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
x.sort()
print(x)

[[0.02390773 0.02414255 0.12634595 0.1634656  0.28382233 0.32423852
  0.33927883 0.86175287 0.86280993 0.94491383]]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

sum_py = sum(arr)

print("Sum using Python sum:", sum_py)

Sum using Python sum: 15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.rand(1,5)
B = np.random.rand(1,5)

print(A == B)

[[False False False False False]]


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
arr_tuble = np.array((1,2,3,4))

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
cartesian_matrix = np.random.rand(10, 2) * 10

r = np.sqrt(cartesian_matrix[:, 0]**2 + cartesian_matrix[:, 1]**2)
theta = np.arctan2(cartesian_matrix[:, 1], cartesian_matrix[:, 0])

theta_degrees = np.degrees(theta)

polar_matrix = np.column_stack((r, theta_degrees))

print("Cartesian Coordinates:")
print(cartesian_matrix)
print("\nPolar Coordinates:")
print(polar_matrix)

Cartesian Coordinates:
[[4.2132144  4.85707755]
 [5.79883762 4.56103539]
 [3.90989668 2.80186583]
 [7.96979741 4.60444499]
 [3.08963986 2.57455936]
 [2.26773777 4.60698868]
 [3.67378134 5.92467722]
 [3.69213891 3.42159889]
 [1.32386606 6.50107689]
 [9.05212629 3.95881797]]

Polar Coordinates:
[[ 6.42980388 49.06038351]
 [ 7.3776393  38.18657415]
 [ 4.81017091 35.62571162]
 [ 9.2042699  30.01660575]
 [ 4.02171983 39.80403319]
 [ 5.13487871 63.79180733]
 [ 6.97126025 58.19772401]
 [ 5.03380857 42.82205425]
 [ 6.63450239 78.48978538]
 [ 9.87994079 23.62147585]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
x = np.random.rand(10)
x.sort
x[-1] = 0
print(x)

[0.10249903 0.74746815 0.38538859 0.87952808 0.72926778 0.96464196
 0.22896334 0.370832   0.01991363 0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
x_coordinates = np.linspace(0, 1, 3)
y_coordinates = np.linspace(0, 1, 3)

x_mesh, y_mesh = np.meshgrid(x_coordinates, y_coordinates)

structured_array = np.column_stack((x_mesh.ravel(), y_mesh.ravel()))

print(structured_array)

[[0.  0. ]
 [0.5 0. ]
 [1.  0. ]
 [0.  0.5]
 [0.5 0.5]
 [1.  0.5]
 [0.  1. ]
 [0.5 1. ]
 [1.  1. ]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

diff_matrix = 1 / (X[:, np.newaxis] - Y)

print("Cauchy Matrix:")
print(diff_matrix)

Cauchy Matrix:
[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
  print(dtype, ":", np.iinfo(dtype).min, np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
  print(dtype, ":", np.finfo(dtype).min, np.finfo(dtype).max, np.finfo(dtype).eps)

<class 'numpy.int8'> : -128 127
<class 'numpy.int32'> : -2147483648 2147483647
<class 'numpy.int64'> : -9223372036854775808 9223372036854775807
<class 'numpy.float32'> : -3.4028235e+38 3.4028235e+38 1.1920929e-07
<class 'numpy.float64'> : -1.7976931348623157e+308 1.7976931348623157e+308 2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
print(X)

[1 2 3]


In [ ]:
for x in X :

  print(x,end = " ")

1 2 3 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
vector = np.array([1, 3, 5, 7, 9])

scalar = 6

absolute_diff = np.abs(vector - scalar)

closest_index = np.argmin(absolute_diff)

closest_value = vector[closest_index]

print("Vector:", vector)
print("Scalar:", scalar)
print("Closest Value:", closest_value)

Vector: [1 3 5 7 9]
Scalar: 6
Closest Value: 5


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
dtype = [('position', [('x', float, 1), ('y', float, 1)]),
         ('color', [('r', float, 1), ('g', float, 1), ('b', float, 1)])]

data = np.zeros(10, dtype=dtype)

data[0]['position']['x'] = 5.2
data[0]['color']['r'] = 1

print(data)

[((5.2, 0.), (1., 0., 0.)) ((0. , 0.), (0., 0., 0.))
 ((0. , 0.), (0., 0., 0.)) ((0. , 0.), (0., 0., 0.))
 ((0. , 0.), (0., 0., 0.)) ((0. , 0.), (0., 0., 0.))
 ((0. , 0.), (0., 0., 0.)) ((0. , 0.), (0., 0., 0.))
 ((0. , 0.), (0., 0., 0.)) ((0. , 0.), (0., 0., 0.))]


<ipython-input-3-e2f66361af84>:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  data = np.zeros(10, dtype=dtype)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
coordinates = np.random.rand(100, 2)

distances = np.sqrt(((coordinates - coordinates[:, None])**2).sum(axis=2))

distances -= np.diag(np.diag(distances))

print(distances)

[[0.         0.34344986 0.53565178 ... 0.79420873 0.90152356 0.27398262]
 [0.34344986 0.         0.43386486 ... 0.45107376 0.62361734 0.42413675]
 [0.53565178 0.43386486 0.         ... 0.62832459 0.47339005 0.3365457 ]
 ...
 [0.79420873 0.45107376 0.62832459 ... 0.         0.41097558 0.81331177]
 [0.90152356 0.62361734 0.47339005 ... 0.41097558 0.         0.78677248]
 [0.27398262 0.42413675 0.3365457  ... 0.81331177 0.78677248 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:

def float_to_int_inplace_clip(float_array):

  float_array[:] = np.clip(float_array, np.iinfo(np.int32).min, np.iinfo(np.int32).max, out=float_array)
  float_array.astype(np.int32)

data = np.random.rand(10).astype(np.float32)
print(f"Original array (float32): {data}")

float_to_int_inplace_clip(data)

print(f"Converted array (int32, clipped): {data}")

Original array (float32): [0.82119316 0.6731493  0.25966105 0.6077339  0.5758792  0.78038484
 0.00490574 0.38723287 0.5530625  0.90812635]
Converted array (int32, clipped): [0.82119316 0.6731493  0.25966105 0.6077339  0.5758792  0.78038484
 0.00490574 0.38723287 0.5530625  0.90812635]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
# import pandas as pd

# x = pd.read_csv(path)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
data = np.arange(12).reshape(3, 4)

for index, value in np.ndenumerate(data):
  print(f"Index: {index}, Value: {value}")

Index: (0, 0), Value: 0
Index: (0, 1), Value: 1
Index: (0, 2), Value: 2
Index: (0, 3), Value: 3
Index: (1, 0), Value: 4
Index: (1, 1), Value: 5
Index: (1, 2), Value: 6
Index: (1, 3), Value: 7
Index: (2, 0), Value: 8
Index: (2, 1), Value: 9
Index: (2, 2), Value: 10
Index: (2, 3), Value: 11


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
size = 10

mu = 0.0
sigma = 1.0

x, y = np.meshgrid(np.linspace(-size/2, size/2, size), np.linspace(-size/2, size/2, size))

d = np.sqrt(x**2 + y**2)

g = np.exp(-( (d - mu)**2 / (2.0 * sigma**2) ))

print(g[:5, :10])

[[1.38879439e-11 1.93776925e-09 7.86683682e-08 9.29249200e-07
  3.19373018e-06 3.19373018e-06 9.29249200e-07 7.86683682e-08
  1.93776925e-09 1.38879439e-11]
 [1.93776925e-09 2.70374774e-07 1.09765093e-05 1.29657100e-04
  4.45617596e-04 4.45617596e-04 1.29657100e-04 1.09765093e-05
  2.70374774e-07 1.93776925e-09]
 [7.86683682e-08 1.09765093e-05 4.45617596e-04 5.26373946e-03
  1.80909100e-02 1.80909100e-02 5.26373946e-03 4.45617596e-04
  1.09765093e-05 7.86683682e-08]
 [9.29249200e-07 1.29657100e-04 5.26373946e-03 6.21765240e-02
  2.13694068e-01 2.13694068e-01 6.21765240e-02 5.26373946e-03
  1.29657100e-04 9.29249200e-07]
 [3.19373018e-06 4.45617596e-04 1.80909100e-02 2.13694068e-01
  7.34443672e-01 7.34443672e-01 2.13694068e-01 1.80909100e-02
  4.45617596e-04 3.19373018e-06]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
def place_elements_loop(array, elements, p):

  rows, cols = len(array), len(array[0])
  placed = 0
  while placed < p:
    i = np.random.randint(0, rows-1)
    j = np.random.randint(0, cols-1)
    if array[i][j] is None:
      array[i][j] = elements.pop(0)
      placed += 1
  return array

array = [[None] * 5 for _ in range(5)]
elements = ["A", "B", "C", "D", "E"]
p = 3
modified_array = place_elements_loop(array, elements.copy(), p)

print("Original Array:")
for row in array:
  print(row)

print("\nModified Array with", p, "elements placed:")
for row in modified_array:
  print(row)

Original Array:
[None, 'C', 'B', None, None]
[None, None, None, None, None]
[None, None, 'A', None, None]
[None, None, None, None, None]
[None, None, None, None, None]

Modified Array with 3 elements placed:
[None, 'C', 'B', None, None]
[None, None, None, None, None]
[None, None, 'A', None, None]
[None, None, None, None, None]
[None, None, None, None, None]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
array = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

mean_of_rows = np.mean(array, axis=1)[:, np.newaxis]
centered_array = array - mean_of_rows

print("Original array:\n", array)
print("\nCentered array:\n", centered_array)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Centered array:
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
array = np.array([[3, 1, 4],
                   [1, 5, 6],
                   [4, 2, 8]])

sorted_array = array[array[:, 1].argsort()]

print("Original array:\n", array)
print("\nSorted array by second column:\n", sorted_array)

Original array:
 [[3 1 4]
 [1 5 6]
 [4 2 8]]

Sorted array by second column:
 [[3 1 4]
 [4 2 8]
 [1 5 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
def has_null_columns(array):

    arr = np.array(array)

    return np.any(np.all(arr == None, axis=0))

array_with_null_columns = [
    [1, None, 3],
    [None, None, None],
    [4, None, 6]
]

array_without_null_columns = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print("Array with null columns:", has_null_columns(array_with_null_columns))
print("Array without null columns:", has_null_columns(array_without_null_columns))

Array with null columns: True
Array without null columns: False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
def find_nearest_value(arr, value):
    nearest = None
    min_difference = float('inf')

    for num in arr:
        difference = abs(num - value)
        if difference < min_difference:
            min_difference = difference
            nearest = num

    return nearest

arr = [1, 3, 5, 7, 9]
given_value = 6
nearest_value = find_nearest_value(arr, given_value)
print("Nearest value to", given_value, "in the array is:", nearest_value)

Nearest value to 6 in the array is: 5


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
def sum_arrays(arr1, arr2):
    iterator1 = np.nditer(arr1)
    iterator2 = np.nditer(arr2)
    result = 0

    while not (iterator1.finished and iterator2.finished):
        result += iterator1[0] + iterator2[0]
        iterator1.iternext()
        iterator2.iternext()

    return result

arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4], [5], [6]])
sum_result = sum_arrays(arr1, arr2)
print("Sum of the arrays:", sum_result)

Sum of the arrays: 21


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, input_array, name=None):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.name = getattr(obj, 'name', None)

arr = NamedArray([[1, 2, 3], [4, 5, 6]], name="MyArray")
print("Array:")
print(arr)
print("Name:", arr.name)

Array:
[[1 2 3]
 [4 5 6]]
Name: MyArray


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
def add_one_at_indices(vector, indices):

    mask = np.zeros_like(vector, dtype=bool)
    mask[indices] = True

    vector[mask] += 1

    return vector

original_vector = np.array([1, 2, 3, 4, 5])
indices_to_increment = np.array([0, 2, 3])

result_vector = add_one_at_indices(original_vector, indices_to_increment)
print("Result vector:", result_vector)

Result vector: [2 2 4 5 5]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
def accumulate_elements(X, F, I):
    F[I] += X
    return F

X = np.array([1, 2, 3])
F = np.zeros(5)
I = np.array([0, 2, 4])

result_array = accumulate_elements(X, F, I)
print("Result array:", result_array)

Result array: [1. 0. 2. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
def count_unique_colors(image):

    reshaped_image = image.reshape(-1, 3)

    unique_colors = np.unique(reshaped_image, axis=0)

    return unique_colors.shape[0]

image = np.random.randint(0, 256, size=(100, 100, 3), dtype=np.uint8)
num_unique_colors = count_unique_colors(image)
print("Number of unique colors in the image:", num_unique_colors)

Number of unique colors in the image: 9996


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
array_4d = np.random.randint(0, 10, size=(2, 3, 4, 5))

sum_last_two_axes = np.sum(array_4d, axis=(-2, -1))

print("Original 4D array:")
print(array_4d)
print("\nSum over the last two axes at once:")
print(sum_last_two_axes)

Original 4D array:
[[[[3 7 0 8 6]
   [2 8 9 5 5]
   [6 0 8 0 3]
   [3 7 2 1 1]]

  [[8 4 6 9 9]
   [0 8 8 7 6]
   [8 0 5 7 6]
   [7 2 7 4 4]]

  [[1 4 8 2 5]
   [8 8 5 5 0]
   [1 1 2 1 4]
   [0 5 6 6 0]]]


 [[[0 4 2 8 6]
   [9 0 2 1 7]
   [5 9 2 6 5]
   [1 4 8 9 3]]

  [[5 4 2 0 1]
   [6 8 6 0 1]
   [9 7 7 1 7]
   [9 0 3 1 2]]

  [[2 3 6 4 4]
   [6 9 0 2 4]
   [3 6 9 3 5]
   [4 9 4 1 2]]]]

Sum over the last two axes at once:
[[ 84 115  72]
 [ 91  79  86]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
def compute_subset_means(D, S):

    unique_indices = np.unique(S)

    subset_means = np.zeros_like(unique_indices, dtype=float)

    for i, idx in enumerate(unique_indices):
        subset_indices = np.where(S == idx)
        subset_values = D[subset_indices]
        subset_means[i] = np.mean(subset_values)

    return subset_means

D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
S = np.array([0, 1, 0, 1, 2, 2, 1, 2, 0, 1])

subset_means = compute_subset_means(D, S)
print("Subset means:", subset_means)

Subset means: [4.33333333 5.75       6.33333333]


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
def diagonal_of_dot_product(A, B):

    dot_product = np.einsum('ij,jk->ik', A, B)

    diagonal = np.diagonal(dot_product)

    return diagonal

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
diagonal = diagonal_of_dot_product(A, B)
print("Diagonal of the dot product:", diagonal)

Diagonal of the dot product: [19 50]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
original_vector = np.array([1, 2, 3, 4, 5])

new_vector = np.zeros(len(original_vector) + (len(original_vector) - 1) * 3, dtype=original_vector.dtype)

new_vector[::4] = original_vector

print("Original vector:", original_vector)
print("New vector with 3 consecutive zeros interleaved between each value:", new_vector)

Original vector: [1 2 3 4 5]
New vector with 3 consecutive zeros interleaved between each value: [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [2]:
array_3d = np.random.rand(5, 5, 3)
array_2d = np.random.rand(5, 5)

result = array_3d * array_2d[:, :, np.newaxis]

print(result)

[[[0.32976413 0.38818357 0.19073147]
  [0.27263905 0.17942402 0.06236169]
  [0.36779092 0.2946461  0.12862132]
  [0.05719162 0.04497645 0.02979044]
  [0.38713677 0.66041072 0.63631217]]

 [[0.65734499 0.13901321 0.2905282 ]
  [0.07412173 0.37515553 0.35180258]
  [0.03718816 0.18734153 0.15568272]
  [0.00917408 0.01195598 0.01150704]
  [0.21542646 0.07989587 0.27033954]]

 [[0.28719273 0.20822907 0.12188652]
  [0.42707219 0.463228   0.25924276]
  [0.42734549 0.30369353 0.36272984]
  [0.08382467 0.09616451 0.01403078]
  [0.33076786 0.28291564 0.18908716]]

 [[0.01752717 0.56949029 0.01756649]
  [0.27180427 0.30041787 0.32154251]
  [0.05054548 0.01771901 0.1335152 ]
  [0.02040992 0.07406902 0.08189201]
  [0.31965576 0.08233301 0.25975743]]

 [[0.41527551 0.05374355 0.39532205]
  [0.41033503 0.00333664 0.10515906]
  [0.15487099 0.41142715 0.39178358]
  [0.25856856 0.20853504 0.34760909]
  [0.65424862 0.68804001 0.02240373]]]


#### 72. How to swap two rows of an array? (★★★)

In [3]:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

array[[0, 1]] = array[[1, 0]]

print(array)

[[4 5 6]
 [1 2 3]
 [7 8 9]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [4]:
triangles = [
    [(0, 0), (1, 0), (0, 1)],
    [(1, 0), (1, 1), (0, 1)],
    [(1, 1), (2, 1), (1, 2)],
    [(0, 1), (1, 2), (0, 2)],
    [(0, 2), (1, 2), (0, 3)],
    [(1, 2), (1, 3), (0, 3)],
    [(1, 3), (2, 3), (1, 4)],
    [(0, 3), (1, 4), (0, 4)],
    [(0, 4), (1, 4), (0, 5)],
    [(1, 4), (1, 5), (0, 5)]
]

def get_segments(triangle):
    segments = []
    for i in range(3):

        segment = (triangle[i], triangle[(i + 1) % 3])
        segments.append(segment)
    return segments

unique_segments = set()

for triangle in triangles:
    segments = get_segments(triangle)
    unique_segments.update(segments)

print("Unique line segments:")
for segment in unique_segments:
    print(segment)

Unique line segments:
((1, 2), (1, 3))
((1, 0), (0, 1))
((0, 3), (1, 2))
((1, 2), (0, 2))
((1, 4), (1, 3))
((1, 2), (0, 3))
((0, 5), (1, 4))
((1, 1), (2, 1))
((1, 4), (1, 5))
((1, 3), (2, 3))
((2, 1), (1, 2))
((1, 2), (1, 1))
((0, 0), (1, 0))
((1, 4), (0, 4))
((0, 5), (0, 4))
((1, 1), (0, 1))
((0, 1), (1, 0))
((2, 3), (1, 4))
((1, 4), (0, 5))
((0, 3), (0, 2))
((0, 3), (1, 4))
((0, 4), (1, 4))
((1, 0), (1, 1))
((0, 1), (0, 0))
((0, 2), (1, 2))
((1, 5), (0, 5))
((0, 1), (1, 2))
((0, 4), (0, 3))
((0, 2), (0, 1))
((1, 3), (0, 3))


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [5]:
C = np.array([0, 1, 1, 2, 2, 3, 4, 4, 4, 4])

max_value = len(C) - 1

A = np.repeat(np.arange(max_value + 1), C)

print("Array A:", A)

print("Is np.bincount(A) equal to C?", np.array_equal(np.bincount(A), C))

Array A: [1 2 3 3 4 4 5 5 5 6 6 6 6 7 7 7 7 8 8 8 8 9 9 9 9]
Is np.bincount(A) equal to C? True


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [6]:
def sliding_window_average(arr, window_size):
    cumsum = np.cumsum(arr)
    cumsum[window_size:] = cumsum[window_size:] - cumsum[:-window_size]
    return cumsum[window_size - 1:] / window_size

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

window_size = 3

averages = sliding_window_average(arr, window_size)

print("Original array:", arr)
print("Sliding window averages (window size =", window_size, "):", averages)

Original array: [ 1  2  3  4  5  6  7  8  9 10]
Sliding window averages (window size = 3 ): [2. 3. 4. 5. 6. 7. 8. 9.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)