In [ ]:
import numpy as np
import platform
print(platform.python_version())
print(np.__version__)

3.10.12
1.25.2


In [ ]:
ar = np.array(range(10))
print(ar)
ar2 = np.arange(0,20,2)
print(ar2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
arr = np.array([1+2j , 3-4j] , dtype= np.complex64)
arr2 = np.array([1,2,3] , dtype= "f4")
arr3 = np.array([0,1,1] , dtype= np.bool_)

print(arr)
print(arr2)
print(arr3)

[1.+2.j 3.-4.j]
[1. 2. 3.]
[False  True  True]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]],dtype = "i2")
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.linspace(0,10,21)
print(arr)
arr , step = np.linspace(0,10,20,endpoint = False , retstep = True)
print(arr)
print(step)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
0.5


In [ ]:
arr = np.random.rand(3,3)
print(arr)

[[0.06336008 0.54966765 0.41885981]
 [0.53433215 0.33447885 0.22962285]
 [0.33960735 0.4760443  0.65155425]]


In [ ]:
arr = np.zeros((2,3))
print(arr)

arr = np.zeros_like(arr2)
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0.]


In [ ]:
arr = np.ones_like(arr2)
print(arr)

[1. 1. 1.]


In [ ]:
empty = np.empty((2,3))
print(empty)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr = np.full((2,3),5)
print(arr)
arr = np.full_like(arr,7)
print(arr)

[[5 5 5]
 [5 5 5]]
[[7 7 7]
 [7 7 7]]


In [ ]:
arr = [1,2,3]
print(np.repeat(arr,3))

arr = [1,2,3]
print(np.tile(arr,3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [ ]:
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr = np.eye(5 , k = 2)
print(arr)

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
print(np.diag(arr3))

[[False False False]
 [False  True False]
 [False False  True]]


In [ ]:
print(len(arr3))

3


In [ ]:
print(arr3.ndim)

1


In [ ]:
x = len(arr3)
print(x*arr3.itemsize)

1


In [ ]:
print(np.random.randint(1,10,3,"i8"))

[1 9 5]


In [ ]:
arr = np.random.choice(range(3),10,replace = True , p = [0.1,0.8,0.1])
print(arr)

[2 1 1 1 1 1 1 2 1 2]


axis = 0 صف
axis = 1 عمود